# This workflow is disabled in favor of nextjs.yml
# Keeping it for reference

name: Deploy to GitHub Pages (Disabled)

on:
  workflow_dispatch: # Only manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build and Export
        run: npm run deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out 